-- ============================================================
-- 02_schema.sql
-- RUN THIS CONNECTED AS  friends_app  (the user created in 01).
--   In Database Actions: sign in as FRIENDS_APP, open SQL, run this.
-- Creates the tables the Streamlit app reads/writes.
-- Safe to re-run: it drops existing tables first.
-- ============================================================

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE kids CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE friends CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE friends (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name         VARCHAR2(200) NOT NULL,
  phone        VARCHAR2(50),
  dob          DATE,
  email        VARCHAR2(200),
  location     VARCHAR2(200),
  anniversary  DATE,
  photo_url    VARCHAR2(1000),
  lat          NUMBER,
  lng          NUMBER,
  created_at   TIMESTAMP DEFAULT SYSTIMESTAMP,
  updated_at   TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE kids (
  id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  friend_id  NUMBER NOT NULL,
  name       VARCHAR2(200) NOT NULL,
  dob        DATE,
  CONSTRAINT fk_kids_friend
    FOREIGN KEY (friend_id) REFERENCES friends(id) ON DELETE CASCADE
);

CREATE INDEX ix_kids_friend ON kids(friend_id);

-- A couple of sample rows so the map isn't empty on first run.
-- (On Autonomous DB, avoid INSERT...SELECT into a child table here: it can run
--  in parallel and deadlock on the FK sibling-row lock. Use single-row VALUES.)
ALTER SESSION DISABLE PARALLEL DML;

INSERT INTO friends (name, phone, dob, email, location, anniversary, photo_url, lat, lng)
VALUES ('Amit Sharma', '+91 98200 11111', DATE '1989-06-20', 'amit@example.com',
        'Mumbai, India', DATE '2015-02-12', 'https://i.pravatar.cc/200?img=11',
        19.0760, 72.8777);

INSERT INTO friends (name, phone, dob, email, location, photo_url, lat, lng)
VALUES ('Sarah Johnson', '+1 415 555 0100', DATE '1991-06-21', 'sarah@example.com',
        'San Francisco, USA', 'https://i.pravatar.cc/200?img=5', 37.7749, -122.4194);

COMMIT;   -- commit parents before inserting children

INSERT INTO kids (friend_id, name, dob)
VALUES ((SELECT id FROM friends WHERE name = 'Amit Sharma'), 'Riya', DATE '2017-09-05');

COMMIT;

-- Verify:
SELECT COUNT(*) AS friends_count FROM friends;
SELECT COUNT(*) AS kids_count    FROM kids;
